[server] # хост и порт которые будут слушаться
host=""
port="3090"

[options]
timeoutGC = 60 # интервал запуска удаления "протухших" ключей
filterKeysWorkers = 5 # количество воркеров фильтрующих ключи при запросе /keys
